# Generated by Django 5.2.3 on 2025-06-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_remove_curso_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cupo',
            field=models.IntegerField(default=20),
        ),
    ]
